# Generated by Django 4.2.27 on 2025-12-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_alter_task_options_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('P1', 'P1 - Do First'), ('P2', 'P2 - Schedule'), ('P3', 'P3 - Quick Win'), ('P4', 'P4 - Backlog')], db_index=True, default='P4', max_length=2),
        ),
    ]
