# Generated by Django 4.2.27 on 2025-12-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_add_category_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TODO', 'To Do'), ('DOING', 'In Progress'), ('WAITING', 'Waiting'), ('DONE', 'Done')], default='TODO', max_length=10),
        ),
    ]
